package hotelideal.Vistas;

import hotelideal.AccesoADatos.TipoHabitacionData;
import hotelideal.Entidades.TipoHabitacion;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

public class FormularioTipoHabitacionView extends javax.swing.JInternalFrame {

    private TipoHabitacionData thd;
    private TipoHabitacion th;

    private int estado;

    public FormularioTipoHabitacionView() {

        initComponents();
        try {
            thd = new TipoHabitacionData();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        th = new TipoHabitacion();

        setFrameIcon(new ImageIcon(getClass().getResource("/icon/logo1.png")));

        estado = 0;

        limpiarDatosTipoHabitacion();

        addSelectAllOnFocusToTextFields(this);

        cargarTipoHabitacion();

        pasarFoco(jcbTipoHabitacion);

    }

    private void cargarTipoHabitacion() {
        jcbTipoHabitacion.removeAllItems();
        for (TipoHabitacion tipoh : thd.buscarTodos()) {
            if (tipoh != null) {
                jcbTipoHabitacion.addItem(tipoh);
            }
        }
    }

    private void limpiarDatosTipoHabitacion() {

        limpiarCampos();
        estadosCampos(false, false, false, false, false, false, false);
        estadosBotones(true, false, false, false);

    }

    private void restaurarDatosTipoHabitacion() {

        estadosBotones(true, true, false, false);
        estadosCampos(false, false, false, false, false, false, false);
        txtId.setText("" + th.getId_tipoDeHabitacion());
        txtDescripcion.setText(th.getDescripcion());
        txtPrecioNoche.setText("" + th.getPrecioNoche());
        txtCamasKing.setText("" + th.getCantKing());
        txtCamasQueen.setText("" + th.getCantQueen());
        txtCamasSimples.setText("" + th.getCantSimple());
        txtCantPer.setText("" + th.getCantPersonas());
        chkActivo.setSelected(th.isEstado());

    }

    private void estadosBotones(boolean btnNuevo, boolean btnEditar, boolean btnGuardar, boolean btnCancelar) {

        cmdNuevo.setEnabled(btnNuevo);
        cmdEditar.setEnabled(btnEditar);
        cmdGuardar.setEnabled(btnGuardar);
        cmdCancelar.setEnabled(btnCancelar);

    }

    private void estadosCampos(boolean tfDescripcion, boolean tfPrecioNoche, boolean tfCamasKing, boolean tfCamasQueen, boolean tfCamasSimples, boolean tfCantPer, boolean ckActivo) {

        txtDescripcion.setEnabled(tfDescripcion);
        txtPrecioNoche.setEnabled(tfPrecioNoche);
        txtCamasKing.setEnabled(tfCamasKing);
        txtCamasQueen.setEnabled(tfCamasQueen);
        txtCamasSimples.setEnabled(tfCamasSimples);
        txtCantPer.setEnabled(tfCantPer);
        chkActivo.setEnabled(ckActivo);

    }

    private void limpiarCampos() {

        txtDescripcion.setText("");
        txtPrecioNoche.setText("");
        txtCamasKing.setText("");
        txtCamasQueen.setText("");
        txtCamasSimples.setText("");
        txtCantPer.setText("");
        chkActivo.setSelected(true);

    }

    private boolean validarDescripcion(String descripcion) {
        return descripcion.matches("^[a-zA-Z0-9\\s-]{1,50}$");
    }

    private boolean validarPrecioNoche(String precioNoche) {
        return precioNoche.matches("^[0-9]+(\\.[0-9]{1,2})?$");
    }

    private boolean validarCantidadCamas(String cantidadCamas) {
        return cantidadCamas.matches("^[0-9]$");
    }

    private boolean validarCantidad(String cantidad) {
        return cantidad.matches("^[1-9]$");
    }

    public static void addSelectAllOnFocusToTextFields(Container container) {
        for (Component component : container.getComponents()) {
            if (component instanceof JTextField) {
                JTextField textField = (JTextField) component;
                textField.addFocusListener(new FocusAdapter() {

                    @Override
                    public void focusGained(FocusEvent e) {
                        textField.selectAll();
                    }
                });
            } else if (component instanceof Container) {
                // Si es un contenedor, busca campos de texto dentro del contenedor
                addSelectAllOnFocusToTextFields((Container) component);
            }
        }
    }

    private void pasarFoco(Component com) {

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {

                com.requestFocusInWindow();

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        lblNom1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        lblNom3 = new javax.swing.JLabel();
        txtNombre3 = new javax.swing.JTextField();
        panel = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblPrecioNoche = new javax.swing.JLabel();
        txtPrecioNoche = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        chkActivo = new javax.swing.JCheckBox();
        cmdNuevo = new javax.swing.JButton();
        cmdEditar = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        lblCamasKing = new javax.swing.JLabel();
        txtCamasKing = new javax.swing.JTextField();
        lblCamasQueen = new javax.swing.JLabel();
        txtCamasQueen = new javax.swing.JTextField();
        lblCamasSimples = new javax.swing.JLabel();
        txtCamasSimples = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcbTipoHabitacion = new javax.swing.JComboBox<>();
        lblCantPer = new javax.swing.JLabel();
        txtCantPer = new javax.swing.JTextField();

        txtId.setText("jTextField1");

        lblNom1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNom1.setText("NOMBRE");

        lblNom3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNom3.setText("NOMBRE");

        setTitle("Tipo Habitacion");
        setToolTipText("");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipo.setText("TIPO DE HAB:");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDescripcion.setText("NOMBRE");

        lblPrecioNoche.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrecioNoche.setText("PRECIO NOCHE");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado.setText("ESTADO");

        chkActivo.setText("ACTIVO");

        cmdNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/New_16.png"))); // NOI18N
        cmdNuevo.setText("Nuevo");
        cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNuevoActionPerformed(evt);
            }
        });

        cmdEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit_File_16.png"))); // NOI18N
        cmdEditar.setText("Editar");
        cmdEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditarActionPerformed(evt);
            }
        });

        cmdSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit_16.png"))); // NOI18N
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });

        cmdGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save_File_16.png"))); // NOI18N
        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });

        cmdCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Cancel_File_16.png"))); // NOI18N
        cmdCancelar.setText("Cancelar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        lblCamasKing.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCamasKing.setText("CAMAS KING");

        lblCamasQueen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCamasQueen.setText("CAMAS QUEEN");

        lblCamasSimples.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCamasSimples.setText("CAMAS SIMPLES");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("FORMULARIO TIPO HABITACION");

        jcbTipoHabitacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTipoHabitacionItemStateChanged(evt);
            }
        });

        lblCantPer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCantPer.setText("CANT PERSONAS");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblEstado)
                        .addGap(18, 18, 18)
                        .addComponent(chkActivo))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(lblCantPer)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantPer, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPrecioNoche)
                                    .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCamasKing)
                                    .addComponent(lblCamasQueen)
                                    .addComponent(lblCamasSimples))
                                .addGap(18, 18, 18)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCamasSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPrecioNoche)
                                        .addComponent(jcbTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCamasKing, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                        .addComponent(txtCamasQueen)
                                        .addComponent(txtDescripcion))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(cmdGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmdCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(cmdNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmdEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmdSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioNoche)
                    .addComponent(txtPrecioNoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCamasKing)
                    .addComponent(txtCamasKing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCamasQueen)
                    .addComponent(txtCamasQueen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCamasSimples)
                    .addComponent(txtCamasSimples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantPer)
                    .addComponent(txtCantPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(chkActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSalir)
                    .addComponent(cmdNuevo)
                    .addComponent(cmdEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdGuardar)
                    .addComponent(cmdCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("TipoHabitacion");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed

        estado = 1;

        limpiarCampos();
        estadosCampos(true, true, true, true, true, true, true);
        estadosBotones(false, false, true, true);
        pasarFoco(txtDescripcion);
        jcbTipoHabitacion.setEnabled(false);

    }//GEN-LAST:event_cmdNuevoActionPerformed

    private void cmdEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditarActionPerformed

        estado = 2;

        estadosCampos(true, true, true, true, true, true, true);
        estadosBotones(false, false, true, true);
        pasarFoco(txtDescripcion);
        jcbTipoHabitacion.setEnabled(false);
    }//GEN-LAST:event_cmdEditarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed

        if (estado == 1) {

            limpiarDatosTipoHabitacion();
            restaurarDatosTipoHabitacion();
            pasarFoco(jcbTipoHabitacion);

        } else if (estado == 2) {

            restaurarDatosTipoHabitacion();
            pasarFoco(cmdEditar);

        } else {
            restaurarDatosTipoHabitacion();          
            pasarFoco(jcbTipoHabitacion);

        }

        estado = 0;
        jcbTipoHabitacion.setEnabled(true);
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed

        if (!validarDescripcion(txtDescripcion.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese una Descripcion Correcta", "Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            pasarFoco(txtDescripcion);
            return;
        }

        if (!validarPrecioNoche(txtPrecioNoche.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese un Precio Correcto", "Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            pasarFoco(txtPrecioNoche);
            return;
        }

        if (!validarCantidadCamas(txtCamasKing.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese una cantidad de Camas King Correcta", "Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            pasarFoco(txtCamasKing);
            return;
        }

        if (!validarCantidadCamas(txtCamasQueen.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese una cantidad de Camas Queen Correcta", "Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            pasarFoco(txtCamasQueen);
            return;
        }

        if (!validarCantidadCamas(txtCamasSimples.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese una cantidad de Camas Simples Correcta", "Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            pasarFoco(txtCamasSimples);
            return;
        }

        if (!validarCantidad(txtCantPer.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese una cantidad de Personas Correcta", "Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            pasarFoco(txtCantPer);
            return;
        }

        if (estado == 1) {
            th = new TipoHabitacion(Integer.parseInt(txtCamasSimples.getText()), Integer.parseInt(txtCamasQueen.getText()), Integer.parseInt(txtCamasKing.getText()), Integer.parseInt(txtCantPer.getText()), "" + txtDescripcion.getText(), Double.parseDouble(txtPrecioNoche.getText()), chkActivo.isSelected());
        } else if (estado == 2) {
            th = new TipoHabitacion(Integer.parseInt(txtId.getText()), Integer.parseInt(txtCamasSimples.getText()), Integer.parseInt(txtCamasQueen.getText()), Integer.parseInt(txtCamasKing.getText()), Integer.parseInt(txtCantPer.getText()), "" + txtDescripcion.getText(), Double.parseDouble(txtPrecioNoche.getText()), chkActivo.isSelected());
        }

        // limpiarDatosHuesped();
        th = thd.guardar(th);

        if (th != null) {
            if (estado == 1) {
                JOptionPane.showConfirmDialog(this, "El Tipo de Habitacion fue agregado correctamente", "Tipo de Habitacion Creado", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            } else if (estado == 2) {
                JOptionPane.showConfirmDialog(this, "El Tipo de Habitacion fue modificado correctamente", "Tipo de Habitacion Modificado", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            }
            restaurarDatosTipoHabitacion();
        }

        estado = 0;
        jcbTipoHabitacion.setEnabled(true);
        pasarFoco(jcbTipoHabitacion);
        cargarTipoHabitacion();
        jcbTipoHabitacion.setSelectedItem(th);
        restaurarDatosTipoHabitacion();
        
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        dispose();
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void jcbTipoHabitacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTipoHabitacionItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            th = (TipoHabitacion) jcbTipoHabitacion.getSelectedItem();
            if (th != null) {
                restaurarDatosTipoHabitacion();
            }
    }//GEN-LAST:event_jcbTipoHabitacionItemStateChanged
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdEditar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdNuevo;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<TipoHabitacion> jcbTipoHabitacion;
    private javax.swing.JLabel lblCamasKing;
    private javax.swing.JLabel lblCamasQueen;
    private javax.swing.JLabel lblCamasSimples;
    private javax.swing.JLabel lblCantPer;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNom1;
    private javax.swing.JLabel lblNom3;
    private javax.swing.JLabel lblPrecioNoche;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtCamasKing;
    private javax.swing.JTextField txtCamasQueen;
    private javax.swing.JTextField txtCamasSimples;
    private javax.swing.JTextField txtCantPer;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre3;
    private javax.swing.JTextField txtPrecioNoche;
    // End of variables declaration//GEN-END:variables

}
