/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelideal.Vistas;


import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import hotelideal.AccesoADatos.TipoUsuarioRepositorio;
import hotelideal.AccesoADatos.UsuarioRepositorio;
import hotelideal.Entidades.TipoUsuario;
import hotelideal.Entidades.Usuario;
import hotelideal.eventos.LoginListener;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class MenuView extends javax.swing.JFrame implements LoginListener {

    static MenuView test;

    private TipoUsuarioRepositorio tr;
    private UsuarioRepositorio ur;

    private Usuario user;
    private TipoUsuario userType;
    private int idSystemUser;

    public MenuView() throws SQLException {

        ur = new UsuarioRepositorio();
        tr = new TipoUsuarioRepositorio();

        initComponents();
        setSize(1280, 720);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/icon/logo1.png")).getImage());

        ImageIcon icon = new ImageIcon(getClass().getResource("/icon/hotel.jpg"));
        Image image = icon.getImage();

        Image newimage = image.getScaledInstance(1280, 720, Image.SCALE_SMOOTH);

        jDesktopPane1 = new javax.swing.JDesktopPane() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(newimage, 0, 0, this);
            }
        };

        setContentPane(jDesktopPane1);

    }

    private void centrarInternalFrame(JInternalFrame form) {

        Dimension desktopSize = jDesktopPane1.getSize();
        int x = (desktopSize.width - form.getWidth()) / 2;
        int y = (desktopSize.height - form.getHeight()) / 2;
        form.setLocation(x, y);
    }

    private void createLogin() throws SQLException {

        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Login frmLogin = new Login();
        frmLogin.setLoginListener((LoginListener) this);
        centrarInternalFrame(frmLogin);
        frmLogin.setVisible(true);
        jDesktopPane1.add(frmLogin);
        jDesktopPane1.moveToFront(frmLogin);

    }

    @Override
    public void onLoginSuccess(int idUser, String username) {

        setTitle(getTitle() + " - USUARIO: " + username);
        idSystemUser = idUser;

    }

    @Override
    public void onMethodExecution() {

        user = ur.buscarPorId(idSystemUser);

        userType = tr.buscarPorId(user.getTipoUsuario().getIdTipoUsuario());

        if (userType.isAdmin()) {

            //estadoMenus(true, true, true, true, true, true);
        } else if (userType.isCrud()) {

            //estadoMenus(true, true, true, false, false, true);
        } else if (userType.isQueries()) {

            //estadoMenus(false, false, false, true, false, true);
        }

    }

//    private void estadoMenus(boolean eMenu1, boolean eMenu2, boolean eMenu3, boolean eMenu4, boolean eMenu5, boolean eMenu6) {
//
//        menu1.setEnabled(eMenu1);
//        menu2.setEnabled(eMenu2);
//        menu3.setEnabled(eMenu3);
//        menu4.setEnabled(eMenu4);
//        menu5.setEnabled(eMenu5);
//        menu6.setEnabled(eMenu6);
//
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuHuesped = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuHabitacion = new javax.swing.JMenuItem();
        menuTipoHabitacion = new javax.swing.JMenuItem();
        planilla = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuReserva = new javax.swing.JMenuItem();
        NuevaReserva = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 965, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        jMenu1.setText("Huesped");

        menuHuesped.setText("Formulario Huesped");
        menuHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHuespedActionPerformed(evt);
            }
        });
        jMenu1.add(menuHuesped);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Habitacion");

        menuHabitacion.setText("Formulario Habitacion");
        menuHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHabitacionActionPerformed(evt);
            }
        });
        jMenu2.add(menuHabitacion);

        menuTipoHabitacion.setText("Formulario Tipo de Habitacion");
        menuTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTipoHabitacionActionPerformed(evt);
            }
        });
        jMenu2.add(menuTipoHabitacion);

        planilla.setText("Planilla De Habitaciones");
        planilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planillaActionPerformed(evt);
            }
        });
        jMenu2.add(planilla);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reserva");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        menuReserva.setText("Manejo de Reservas");
        menuReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReservaActionPerformed(evt);
            }
        });
        jMenu3.add(menuReserva);

        NuevaReserva.setText("Nueva Reservación");
        NuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaReservaActionPerformed(evt);
            }
        });
        jMenu3.add(NuevaReserva);

        jMenuBar1.add(jMenu3);

        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {

            //estadoMenus(false, false, false, false, false, false);
            createLogin();

        } catch (SQLException ex) {

            JOptionPane.showConfirmDialog(this, ex.getMessage(), "Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_formWindowOpened

    private void menuHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHuespedActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioHuespedView frmHuesped = new FormularioHuespedView();
        centrarInternalFrame(frmHuesped);
        frmHuesped.setVisible(true);
        jDesktopPane1.add(frmHuesped);
        jDesktopPane1.moveToFront(frmHuesped);
    }//GEN-LAST:event_menuHuespedActionPerformed

    private void menuHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHabitacionActionPerformed
        try {
            jDesktopPane1.removeAll();
            jDesktopPane1.repaint();
            FormularioHabitacionView fhv = new FormularioHabitacionView();
            centrarInternalFrame(fhv);
            fhv.setVisible(true);
            jDesktopPane1.add(fhv);
            jDesktopPane1.moveToFront(fhv);
        } catch (SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuHabitacionActionPerformed

    private void menuReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReservaActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        GestionReservas gestionReservas = new GestionReservas();
        centrarInternalFrame(gestionReservas);
        gestionReservas.setVisible(true);
        jDesktopPane1.add(gestionReservas);
        jDesktopPane1.moveToFront(gestionReservas);
    }//GEN-LAST:event_menuReservaActionPerformed

    private void menuTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTipoHabitacionActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioTipoHabitacionView frmTH = new FormularioTipoHabitacionView();
        centrarInternalFrame(frmTH);
        frmTH.setVisible(true);
        jDesktopPane1.add(frmTH);
        jDesktopPane1.moveToFront(frmTH);
    }//GEN-LAST:event_menuTipoHabitacionActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSalirMouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void NuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaReservaActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioReservaView frmReseva = new FormularioReservaView();
        centrarInternalFrame(frmReseva);
        frmReseva.setVisible(true);
        jDesktopPane1.add(frmReseva);
        jDesktopPane1.moveToFront(frmReseva);
    }//GEN-LAST:event_NuevaReservaActionPerformed

    private void planillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planillaActionPerformed
        try {
            jDesktopPane1.removeAll();
            jDesktopPane1.repaint();
            PlanillaHabitaciones ph = new PlanillaHabitaciones();
            centrarInternalFrame(ph);
            ph.setVisible(true);
            jDesktopPane1.add(ph);
            jDesktopPane1.moveToFront(ph);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_planillaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("theme");
//        FlatMacDarkLaf.setup();
//        FlatLightLaf.setup();
//#BF5AF2 #f00 #00C #6FF #33ffff #6ccff
        //FlatLaf.setGlobalExtraDefaults(Collections.singletonMap("@accentColor", "#6ccff"));
        FlatDarculaLaf.setup();

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                try {

                    new MenuView().setVisible(true);

                } catch (SQLException ex) {

                    JOptionPane.showConfirmDialog(null, ex.getMessage(), "Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);

                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem NuevaReserva;
    private static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuHabitacion;
    private javax.swing.JMenuItem menuHuesped;
    private javax.swing.JMenuItem menuReserva;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem menuTipoHabitacion;
    private javax.swing.JMenuItem planilla;
    // End of variables declaration//GEN-END:variables

    public static JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }
}
